# Site settings
title: Smarter Together
email: michal@waat.eu
description: > # this means to ignore newlines until "baseurl:"
  SMARTER TOGETHER will prepare the ground for large-scale replication
  and ensure an in-depth knowledge transfer about setting up of smart
  city business models and user-centric innovation in order to
  contribute to positive societal dynamics.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://smarter-together.eu" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
collections:
  events:
    output: true
  news:
    output: true

# Publish posts or collection documents with a future date.
future: true

# Build settings
markdown: kramdown

# Override Jekyll's default _site destination with proper label
destination: ./_site

# Keep symbolic links to theme libraries
keep_files: [bootstrap-sass, css, images, js]

# Exclude dirs and files that should not be copied into rendered prototype
exclude: [node_modules, sass, styleguide, templates, Gemfile, Gruntfile.js, gulpfile.js, package.json, README.md, feed.xml, template.php]

gems:
  - jekyll-paginate-v2

permalink: pretty

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  #title: ':title - page :num'
  #title: ':title | :num of :max'
  title: ':title'

  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

############################################################

# Prose.io configuration
prose:
  siteurl: 'http://smarter-together.eu'
  media: 'images'
  ignore:
    # Jekyll files
    - /_layouts
    - /_includes
    - /_plugins
    - /_posts
    - /_site
    - _config.yml
    # Other files
    - /bootstrap-sass
    - /css
    - /sass
    - /js
    - .gitignore
    - CNAME
    - feed.xml
    - Gemfile
    - gulpfile.js
    - LICENSE
    - package.json
    - README.md

  metadata:
    cities:
      - name: imageurl
        field:
          element: "text"
          label: "Header image URL"
          help: "Addres of the image to be placed in page header section"
          value: "/images/header-default.png"
      - name: layout
        field:
          element: "select"
          label: "Used page layout"
          value: "subpage"
          options:
            - name: 'Subpage'
              value: 'subpage'

    results:
      - name: imageurl
        field:
          element: "text"
          label: "Header image URL"
          help: "Addres of the image to be placed in page header section"
          value: "/images/header-default.png"
      - name: layout
        field:
          element: "select"
          label: "Used page layout"
          value: "subpage"
          options:
            - name: 'Subpage'
              value: 'subpage'

    solutions:
      - name: imageurl
        field:
          element: "text"
          label: "Header image URL"
          help: "Addres of the image to be placed in page header section"
          value: "/images/header-default.png"
      - name: layout
        field:
          element: "select"
          label: "Used page layout"
          value: "subpage"
          options:
            - name: 'Subpage'
              value: 'subpage'
